// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbmFYLmeRkYDlrbxXjpEqLYXDK7NGc9pY',
    appId: '1:563927162216:web:b9ea3c581079261981cadd',
    messagingSenderId: '563927162216',
    projectId: 'mealapp-4faf4',
    authDomain: 'mealapp-4faf4.firebaseapp.com',
    storageBucket: 'mealapp-4faf4.firebasestorage.app',
    measurementId: 'G-MSWFT94STV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjAMiVN85et9doL-UXf70juPR_-xaG1s',
    appId: '1:563927162216:android:c411b788f82479c581cadd',
    messagingSenderId: '563927162216',
    projectId: 'mealapp-4faf4',
    storageBucket: 'mealapp-4faf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXcKLdF9SdEc8p7HLZka7SKnMERdbGC-g',
    appId: '1:563927162216:ios:bda1233385d5fd2c81cadd',
    messagingSenderId: '563927162216',
    projectId: 'mealapp-4faf4',
    storageBucket: 'mealapp-4faf4.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXcKLdF9SdEc8p7HLZka7SKnMERdbGC-g',
    appId: '1:563927162216:ios:bda1233385d5fd2c81cadd',
    messagingSenderId: '563927162216',
    projectId: 'mealapp-4faf4',
    storageBucket: 'mealapp-4faf4.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbmFYLmeRkYDlrbxXjpEqLYXDK7NGc9pY',
    appId: '1:563927162216:web:fa0a544615dbbb5381cadd',
    messagingSenderId: '563927162216',
    projectId: 'mealapp-4faf4',
    authDomain: 'mealapp-4faf4.firebaseapp.com',
    storageBucket: 'mealapp-4faf4.firebasestorage.app',
    measurementId: 'G-9K41PHH3H1',
  );
}
